### ISSUE TITLE
Really long build time

### ISSUE THREAD

**Issue by MightyPancake** [Larpon/miniaudio#11]
Hey there,
the wrapper works just fine, but the module adds **A LOT** (like, 5-10 seconds) to compile time (Windows, tried gcc because tcc didn't work). Do you think this might be resolved in any way or is it just miniaudio being huge?

**Comment by Larpon** [comment]
I can't really do anything about the C compile times. I can recommend investing some time trying to get `tcc` working on your machine OR alternatively develop your apps on linix or macOS and then compile for Windows when you're ready for release. V is no fun without the rapid development cycle IMHO
