### ISSUE TITLE
X module

### ISSUE THREAD

**Issue by LandStander27** [Larpon/miniaudio#12]
Hello
Compiling using the normal `miniaudio` module works fine, but once add `import miniaudio.x`, it errors on compile.
Because the error is so big, I have uploaded it onto pastebin instead.
https://pastebin.com/USqTrcP1

**Comment by Larpon** [comment]
@LandStander27 please try again with latest commits - and feel free to open this issue again if the problem persists
Credits to @spytheman in #14 for fixing the Windows issues!

**Comment by Larpon** [comment]
If you update latest V via `.\makebat` compiling via `tcc` should also work
