### ISSUE TITLE
Build errors when using miniaudio auto generated wrapper

### ISSUE THREAD

**Issue by marcosantos98** [Larpon/miniaudio#13]
### Background

- Added as submodule on project root
- imported with `import miniaudio`
- Fixed by explicit typing `sound_source_channel_count` with u32

### Build error after `import miniaudio`

```v
miniaudio/miniaudio.auto.c.v:10405:40: error: overflow in implicit type `int`, use explicit type casting instead
10403 | }
10404 | 
10405 | pub const sound_source_channel_count = 0xFFFFFFFF
      |                                        ~~~~~~~~~~
10406 | 
10407 | [typedef]
```

### Environment
- V 0.3.2 a60f34e
- Arch Linux 6.1.1

**Comment by Larpon** [comment]
Should be fixed in [b6c2e15](https://github.com/Larpon/miniaudio/commit/b6c2e1559cd8e068be271158aff870d9add1cbc4)
