### ISSUE TITLE
miniaudio module broken, C structs apparently interfere with V's stdlib

### ISSUE THREAD

**Issue by ttytm** [Larpon/miniaudio#16]
Thanks a lot for the module @Larpon!

At some point in the recent past It must have broken.
E.g., I was using it in an app. Now I can't successfully compile it anymore due to an error from miniaudio. 

Trying to compile it results in:
```
/opt/hostedtoolcache/v/0.4.2/x64/vlib/sync/sync_default.c.v:52:8: error: struct `C.pthread_mutex_t` was declared as private to module `miniaudio`, so it can not be used inside module `sync`
   50 | [heap]
   51 | pub struct Mutex {
   52 |     mutex C.pthread_mutex_t
      |           ~~~~~~~~~~~~~~~~~
   53 | }
   54 |
Error: Process completed with exit code 1.
```

Ref.: https://github.com/ttytm/emoji-mart-desktop/actions/runs/6599637443/job/17928908286

Looks like the C struct clashes with the struct in sync, though I'm not actively importing or using sync in the app.

**Comment by Larpon** [comment]
Glad you find it useful.

Yeah this period is a tough time for old C bindings 😅 

I think it can simply be fixed by making one of the definitions `pub` - I'll have a look ASAP

**Comment by Larpon** [comment]
@ttytm - I've just pushed [e706fed](https://github.com/Larpon/miniaudio/commit/e706fed6e966aafd9f4c5d3e620a519af263427c) which should fix the problem.

**Comment by Larpon** [comment]
Oh dear, I'll have a look and see if I can replicate the error locally later

**Comment by Larpon** [comment]
Right I've made a PR <https://github.com/vlang/v/pull/19651> that should fix V's side of the problem (for now).
And have updated `miniaudio` to match V's `sync` module's definition of the struct in 3594e83

**Comment by Larpon** [comment]
V PR has been merged - it should work again :+1:
